[package]
name = "playgame"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[dependencies]
shuttle-service = { version = "0.11.0", features = ["web-actix-web"] }
actix-web = "4.3.1"
rand = "0.8.4"
